const User = require('../../features/auth/models/User');
const Incident = require('../../features/incidents/models/Incident');

/** Nairobi-area coordinates (approx.) for map features and responder routing */
const LOC = {
  cbd: [-1.2864, 36.8172],
  westlands: [-1.2676, 36.8113],
  karen: [-1.3197, 36.7081],
  eastleigh: [-1.2831, 36.8476],
  ngara: [-1.2767, 36.8254],
  trm: [-1.2189, 36.8889],
  kasarani: [-1.2233, 36.8991],
  rongai: [-1.3961, 36.7544],
  muthaiga: [-1.2521, 36.8044],
  kilimani: [-1.2895, 36.786],
  lavington: [-1.2822, 36.7686],
  industrial: [-1.3221, 36.8511],
  airport: [-1.3192, 36.9278],
};

function at([lat, lng], seed) {
  const n = ((seed * 7919) % 1000) / 80000 - 0.00625;
  const m = ((seed * 6971) % 1000) / 80000 - 0.00625;
  return { latitude: lat + n, longitude: lng + m };
}

async function seedDatabase() {
  const existingUsersCount = await User.countDocuments();
  if (existingUsersCount > 0) {
    return;
  }

  const users = [
    {
      id: 'u-admin-1',
      fullname: 'Grace Wambui',
      email: 'admin@safereport.com',
      phone: '+254700000001',
      password: 'admin123',
      role: 'admin',
    },
    {
      id: 'u-admin-2',
      fullname: 'Peter Otieno',
      email: 'p.otieno@safereport.com',
      phone: '+254700000011',
      password: 'admin123',
      role: 'admin',
    },
    {
      id: 'u-reporter-1',
      fullname: 'John Doe',
      email: 'johndoe@gmail.com',
      phone: '+2547361907387',
      password: 'reporter123',
      role: 'reporter',
    },
    {
      id: 'u-reporter-2',
      fullname: 'Amina Hassan',
      email: 'amina.hassan@mail.com',
      phone: '+254722100201',
      password: 'reporter123',
      role: 'reporter',
    },
    {
      id: 'u-reporter-3',
      fullname: 'David Kimani',
      email: 'd.kimani@gmail.com',
      phone: '+254733200302',
      password: 'reporter123',
      role: 'reporter',
    },
    {
      id: 'u-reporter-4',
      fullname: 'Lucy Njeri',
      email: 'lucy.njeri@outlook.com',
      phone: '+254711300403',
      password: 'reporter123',
      role: 'reporter',
    },
    {
      id: 'u-reporter-5',
      fullname: 'Brian Omondi',
      email: 'brian.omondi@yahoo.com',
      phone: '+254725400504',
      password: 'reporter123',
      role: 'reporter',
    },
    {
      id: 'u-reporter-6',
      fullname: 'Fatma Ali',
      email: 'fatma.ali@mail.com',
      phone: '+254737500605',
      password: 'reporter123',
      role: 'reporter',
    },
    {
      id: 'u-reporter-7',
      fullname: 'Stephen Mutua',
      email: 's.mutua@gmail.com',
      phone: '+254720600706',
      password: 'reporter123',
      role: 'reporter',
    },
    {
      id: 'u-reporter-8',
      fullname: 'Wanjiku Mwangi',
      email: 'wanjiku.m@gmail.com',
      phone: '+254734700807',
      password: 'reporter123',
      role: 'reporter',
    },
    {
      id: 'u-responder-1',
      fullname: 'Responder Jane',
      email: 'responder@safereport.com',
      phone: '+254700000002',
      password: 'responder123',
      role: 'responder',
    },
    {
      id: 'u-responder-2',
      fullname: 'James Kiprop',
      email: 'j.kiprop@safereport.com',
      phone: '+254700000003',
      password: 'responder123',
      role: 'responder',
    },
    {
      id: 'u-responder-3',
      fullname: 'Mary Akinyi',
      email: 'm.akinyi@safereport.com',
      phone: '+254700000004',
      password: 'responder123',
      role: 'responder',
    },
    {
      id: 'u-responder-4',
      fullname: 'Tom Barasa',
      email: 't.barasa@safereport.com',
      phone: '+254700000005',
      password: 'responder123',
      role: 'responder',
    },
    {
      id: 'u-responder-5',
      fullname: 'Ruth Chebet',
      email: 'r.chebet@safereport.com',
      phone: '+254700000006',
      password: 'responder123',
      role: 'responder',
    },
    {
      id: 'u-responder-6',
      fullname: 'Eric Mutiso',
      email: 'e.mutiso@safereport.com',
      phone: '+254700000007',
      password: 'responder123',
      role: 'responder',
    },
  ];

  await User.insertMany(users);

  const reporters = [
    'u-reporter-1',
    'u-reporter-2',
    'u-reporter-3',
    'u-reporter-4',
    'u-reporter-5',
    'u-reporter-6',
    'u-reporter-7',
    'u-reporter-8',
  ];

  const incidentTemplates = [
    {
      id: 'INC-2026001',
      type: 'Medical Emergency',
      description:
        'Pedestrian collapsed near bus stop; bystanders performing first aid until help arrives.',
      location: 'Tom Mboya Street, CBD',
      base: LOC.cbd,
      status: 'In Progress',
      priority: 'High',
      responderId: 'u-responder-1',
      createdAt: new Date('2026-02-13T09:15:00.000Z'),
    },
    {
      id: 'INC-2026002',
      type: 'Fire & Rescue',
      description: 'Smoke visible from third floor of residential building; families evacuating.',
      location: 'Eastleigh Section III',
      base: LOC.eastleigh,
      status: 'Completed',
      priority: 'Critical',
      responderId: 'u-responder-2',
      createdAt: new Date('2026-02-09T18:30:00.000Z'),
    },
    {
      id: 'INC-2026003',
      type: 'Crime & Safety',
      description: 'Suspicious individuals loitering near closed shop after hours.',
      location: 'Ngara Market area',
      base: LOC.ngara,
      status: 'Unassigned',
      priority: 'Medium',
      responderId: null,
      createdAt: new Date('2026-02-15T20:05:00.000Z'),
    },
    {
      id: 'INC-2026004',
      type: 'Road & Transport',
      description: 'Multi-vehicle collision blocking one lane; traffic police requested.',
      location: 'Thika Road near TRM',
      base: LOC.trm,
      status: 'Assigned',
      priority: 'High',
      responderId: 'u-responder-3',
      createdAt: new Date('2026-02-16T07:40:00.000Z'),
    },
    {
      id: 'INC-2026005',
      type: 'Natural Disaster',
      description: 'Localized flooding after heavy rain; vehicles stuck in low section.',
      location: 'Industrial Area',
      base: LOC.industrial,
      status: 'In Progress',
      priority: 'High',
      responderId: 'u-responder-4',
      createdAt: new Date('2026-02-14T16:22:00.000Z'),
    },
    {
      id: 'INC-2026006',
      type: 'Public Safety & Welfare',
      description: 'Crowd gathering; loud altercation reported outside venue.',
      location: 'Westlands',
      base: LOC.westlands,
      status: 'Completed',
      priority: 'Medium',
      responderId: 'u-responder-1',
      createdAt: new Date('2026-02-10T22:10:00.000Z'),
    },
    {
      id: 'INC-2026007',
      type: 'Medical Emergency',
      description: 'Child with breathing difficulty; parent requesting ambulance.',
      location: 'Karen',
      base: LOC.karen,
      status: 'Assigned',
      priority: 'Critical',
      responderId: 'u-responder-5',
      createdAt: new Date('2026-02-17T11:05:00.000Z'),
    },
    {
      id: 'INC-2026008',
      type: 'Fire & Rescue',
      description: 'Small electrical fire in kitchen; power isolated by building manager.',
      location: 'Kilimani',
      base: LOC.kilimani,
      status: 'Completed',
      priority: 'Medium',
      responderId: 'u-responder-2',
      createdAt: new Date('2026-02-08T14:00:00.000Z'),
    },
    {
      id: 'INC-2026009',
      type: 'Crime & Safety',
      description: 'Report of phone snatching along footpath.',
      location: 'Lavington',
      base: LOC.lavington,
      status: 'Unassigned',
      priority: 'Medium',
      responderId: null,
      createdAt: new Date('2026-02-18T08:55:00.000Z'),
    },
    {
      id: 'INC-2026010',
      type: 'Other',
      description: 'Fallen tree branch blocking residential access road.',
      location: 'Muthaiga',
      base: LOC.muthaiga,
      status: 'Completed',
      priority: 'Low',
      responderId: 'u-responder-6',
      createdAt: new Date('2026-02-07T09:30:00.000Z'),
    },
    {
      id: 'INC-2026011',
      type: 'Road & Transport',
      description: 'Matatu breakdown causing congestion at roundabout.',
      location: 'Kasarani',
      base: LOC.kasarani,
      status: 'In Progress',
      priority: 'Low',
      responderId: 'u-responder-3',
      createdAt: new Date('2026-02-17T17:45:00.000Z'),
    },
    {
      id: 'INC-2026012',
      type: 'Medical Emergency',
      description: 'Elderly person disoriented; needs welfare check.',
      location: 'Ngong Road area',
      base: LOC.kilimani,
      status: 'Assigned',
      priority: 'Medium',
      responderId: 'u-responder-5',
      createdAt: new Date('2026-02-16T12:20:00.000Z'),
    },
    {
      id: 'INC-2026013',
      type: 'Natural Disaster',
      description: 'Mudslide risk reported on steep embankment after rains.',
      location: 'Rongai',
      base: LOC.rongai,
      status: 'Unassigned',
      priority: 'High',
      responderId: null,
      createdAt: new Date('2026-02-15T06:15:00.000Z'),
    },
    {
      id: 'INC-2026014',
      type: 'Fire & Rescue',
      description: 'Grass fire spreading toward fence line.',
      location: 'JKIA vicinity',
      base: LOC.airport,
      status: 'In Progress',
      priority: 'High',
      responderId: 'u-responder-4',
      createdAt: new Date('2026-02-18T13:00:00.000Z'),
    },
    {
      id: 'INC-2026015',
      type: 'Public Safety & Welfare',
      description: 'Unsafe building debris on sidewalk reported to county.',
      location: 'CBD',
      base: LOC.cbd,
      status: 'Completed',
      priority: 'Low',
      responderId: 'u-responder-1',
      createdAt: new Date('2026-02-06T10:00:00.000Z'),
    },
    {
      id: 'INC-2026016',
      type: 'Crime & Safety',
      description: 'Break-in alarm; unclear if occupants home.',
      location: 'Westlands',
      base: LOC.westlands,
      status: 'Assigned',
      priority: 'High',
      responderId: 'u-responder-6',
      createdAt: new Date('2026-02-17T23:40:00.000Z'),
    },
    {
      id: 'INC-2026017',
      type: 'Medical Emergency',
      description: 'Workplace injury; cut requiring stitches.',
      location: 'Industrial Area',
      base: LOC.industrial,
      status: 'Completed',
      priority: 'Medium',
      responderId: 'u-responder-5',
      createdAt: new Date('2026-02-05T11:25:00.000Z'),
    },
    {
      id: 'INC-2026018',
      type: 'Road & Transport',
      description: 'Oil spill on curve; multiple skidding near-misses.',
      location: 'Thika Road',
      base: LOC.trm,
      status: 'In Progress',
      priority: 'High',
      responderId: 'u-responder-2',
      createdAt: new Date('2026-02-18T05:50:00.000Z'),
    },
    {
      id: 'INC-2026019',
      type: 'Other',
      description: 'Large pothole damaging vehicles; temporary cones requested.',
      location: 'Eastleigh',
      base: LOC.eastleigh,
      status: 'Unassigned',
      priority: 'Low',
      responderId: null,
      createdAt: new Date('2026-02-14T15:10:00.000Z'),
    },
    {
      id: 'INC-2026020',
      type: 'Natural Disaster',
      description: 'Hail damage to market stalls; vendors need assistance tally.',
      location: 'Ngara',
      base: LOC.ngara,
      status: 'Completed',
      priority: 'Medium',
      responderId: 'u-responder-3',
      createdAt: new Date('2026-02-04T16:40:00.000Z'),
    },
    {
      id: 'INC-2026021',
      type: 'Fire & Rescue',
      description: 'Vehicle engine fire extinguished by driver; scene cooling.',
      location: 'Karen',
      base: LOC.karen,
      status: 'Completed',
      priority: 'Medium',
      responderId: 'u-responder-4',
      createdAt: new Date('2026-02-12T19:20:00.000Z'),
    },
    {
      id: 'INC-2026022',
      type: 'Medical Emergency',
      description: 'Allergic reaction at restaurant; staff called emergency line.',
      location: 'Kilimani',
      base: LOC.kilimani,
      status: 'Assigned',
      priority: 'High',
      responderId: 'u-responder-1',
      createdAt: new Date('2026-02-18T20:15:00.000Z'),
    },
    {
      id: 'INC-2026023',
      type: 'Crime & Safety',
      description: 'Harassment report near public transport terminus.',
      location: 'CBD',
      base: LOC.cbd,
      status: 'In Progress',
      priority: 'Medium',
      responderId: 'u-responder-6',
      createdAt: new Date('2026-02-17T14:30:00.000Z'),
    },
    {
      id: 'INC-2026024',
      type: 'Public Safety & Welfare',
      description: 'Open manhole cover hazard on pedestrian path.',
      location: 'Lavington',
      base: LOC.lavington,
      status: 'Unassigned',
      priority: 'Medium',
      responderId: null,
      createdAt: new Date('2026-02-16T09:00:00.000Z'),
    },
    {
      id: 'INC-2026025',
      type: 'Road & Transport',
      description: 'Stray livestock on highway shoulder; risk to motorists.',
      location: 'Rongai',
      base: LOC.rongai,
      status: 'Assigned',
      priority: 'Medium',
      responderId: 'u-responder-2',
      createdAt: new Date('2026-02-15T13:45:00.000Z'),
    },
    {
      id: 'INC-2026026',
      type: 'Medical Emergency',
      description: 'Pregnancy-related emergency; en route to facility.',
      location: 'Kasarani',
      base: LOC.kasarani,
      status: 'Completed',
      priority: 'Critical',
      responderId: 'u-responder-5',
      createdAt: new Date('2026-02-03T04:10:00.000Z'),
    },
    {
      id: 'INC-2026027',
      type: 'Fire & Rescue',
      description: 'Dumpster smoldering behind commercial block.',
      location: 'Industrial Area',
      base: LOC.industrial,
      status: 'Completed',
      priority: 'Low',
      responderId: 'u-responder-4',
      createdAt: new Date('2026-02-11T21:35:00.000Z'),
    },
    {
      id: 'INC-2026028',
      type: 'Natural Disaster',
      description: 'River overflow affecting access road to estate.',
      location: 'Muthaiga',
      base: LOC.muthaiga,
      status: 'In Progress',
      priority: 'High',
      responderId: 'u-responder-3',
      createdAt: new Date('2026-02-18T07:00:00.000Z'),
    },
    {
      id: 'INC-2026029',
      type: 'Other',
      description: 'Chemical smell reported near warehouse; ventilation check.',
      location: 'JKIA cargo area',
      base: LOC.airport,
      status: 'Assigned',
      priority: 'High',
      responderId: 'u-responder-4',
      createdAt: new Date('2026-02-17T10:10:00.000Z'),
    },
    {
      id: 'INC-2026030',
      type: 'Crime & Safety',
      description: 'Vandalism at community notice board; CCTV reference filed.',
      location: 'Westlands',
      base: LOC.westlands,
      status: 'Completed',
      priority: 'Low',
      responderId: 'u-responder-6',
      createdAt: new Date('2026-02-02T18:00:00.000Z'),
    },
    {
      id: 'INC-2026031',
      type: 'Medical Emergency',
      description: 'Heat exhaustion at outdoor event; first aid tent overwhelmed.',
      location: 'Ngong Road',
      base: LOC.kilimani,
      status: 'In Progress',
      priority: 'Medium',
      responderId: 'u-responder-5',
      createdAt: new Date('2026-02-18T12:45:00.000Z'),
    },
    {
      id: 'INC-2026032',
      type: 'Road & Transport',
      description: 'Cyclist struck by opening car door; minor injuries.',
      location: 'Kilimani',
      base: LOC.kilimani,
      status: 'Assigned',
      priority: 'Medium',
      responderId: 'u-responder-1',
      createdAt: new Date('2026-02-16T18:20:00.000Z'),
    },
    {
      id: 'INC-2026033',
      type: 'Public Safety & Welfare',
      description: 'Unsafe scaffolding on construction site reported by neighbor.',
      location: 'Eastleigh',
      base: LOC.eastleigh,
      status: 'Unassigned',
      priority: 'High',
      responderId: null,
      createdAt: new Date('2026-02-18T15:30:00.000Z'),
    },
    {
      id: 'INC-2026034',
      type: 'Fire & Rescue',
      description: 'Alarm activation in office tower; investigation in progress.',
      location: 'Westlands',
      base: LOC.westlands,
      status: 'Assigned',
      priority: 'Medium',
      responderId: 'u-responder-2',
      createdAt: new Date('2026-02-17T08:15:00.000Z'),
    },
    {
      id: 'INC-2026035',
      type: 'Medical Emergency',
      description: 'Diabetic emergency; glucose kit administered by nurse on site.',
      location: 'CBD',
      base: LOC.cbd,
      status: 'Completed',
      priority: 'High',
      responderId: 'u-responder-5',
      createdAt: new Date('2026-02-01T13:50:00.000Z'),
    },
    {
      id: 'INC-2026036',
      type: 'Crime & Safety',
      description: 'Suspicious package left unattended; area cordoned.',
      location: 'TRM',
      base: LOC.trm,
      status: 'In Progress',
      priority: 'Critical',
      responderId: 'u-responder-6',
      createdAt: new Date('2026-02-18T16:00:00.000Z'),
    },
    {
      id: 'INC-2026037',
      type: 'Natural Disaster',
      description: 'Lightning strike damaged transformer; power outage affecting clinic.',
      location: 'Karen',
      base: LOC.karen,
      status: 'Assigned',
      priority: 'High',
      responderId: 'u-responder-3',
      createdAt: new Date('2026-02-14T20:00:00.000Z'),
    },
    {
      id: 'INC-2026038',
      type: 'Road & Transport',
      description: 'Fuel tanker slow leak; hazmat awareness requested.',
      location: 'Industrial Area',
      base: LOC.industrial,
      status: 'Unassigned',
      priority: 'Critical',
      responderId: null,
      createdAt: new Date('2026-02-18T03:25:00.000Z'),
    },
    {
      id: 'INC-2026039',
      type: 'Other',
      description: 'Noise complaint: prolonged drilling after permitted hours.',
      location: 'Lavington',
      base: LOC.lavington,
      status: 'Completed',
      priority: 'Low',
      responderId: 'u-responder-1',
      createdAt: new Date('2026-01-30T22:00:00.000Z'),
    },
    {
      id: 'INC-2026040',
      type: 'Public Safety & Welfare',
      description: 'Lost child reunited with guardian at mall security.',
      location: 'TRM',
      base: LOC.trm,
      status: 'Completed',
      priority: 'Medium',
      responderId: 'u-responder-2',
      createdAt: new Date('2026-02-13T14:40:00.000Z'),
    },
  ];

  const incidents = incidentTemplates.map((row, index) => {
    const coords = at(row.base, index);
    const reporterId = reporters[index % reporters.length];
    return {
      id: row.id,
      reporterId,
      type: row.type,
      description: row.description,
      location: row.location,
      latitude: coords.latitude,
      longitude: coords.longitude,
      status: row.status,
      priority: row.priority,
      responderId: row.responderId,
      createdAt: row.createdAt,
    };
  });

  await Incident.insertMany(incidents);
}

module.exports = seedDatabase;
